language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
bundler_args: --without=localdev
gemfile:
  - gemfiles/chef_10_latest.gemfile
  - gemfiles/chef_11_latest.gemfile
matrix:
  allow_failures:
    - rvm: 2.0.0
notifications:
  webhooks: https://www.buildheroes.com/api/projects/d63f108036d7543765d6f237aa5c5dfa859b90c5/builds
