language: ruby
cache: bundler
sudo: false

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
bundler_args: --without=localdev
gemfile:
  - gemfiles/chef_10_latest.gemfile
  - gemfiles/chef_11_latest.gemfile
  - gemfiles/chef_12_latest.gemfile
